In [ ]:
###DB connection from google 

#function to insert data into database
def insertIntoDatabase():
    try:
         # Establishing the connection to MySQL server (without specifying a database)
        connection = mysql.connector.connect(host='127.0.0.1',
                                             port=3309,
                                             database='webscrape',
                                             user='root',
                                             password='password',
                                             auth_plugin='mysql_native_password')
        if connection.is_connected():
            db_Info = connection.get_server_info()
            print("Connected to MySQL Server version ", db_Info)
            cursor = connection.cursor()
            cursor.execute("select database();")
            record = cursor.fetchone()
            print("You're connected to database: ", record)
            
            # print(connection)
        cursor = connection.cursor()
        # List of table creation queries
        table_creation_queries = ["""CREATE TABLE IF NOT EXISTS currencies (id INT AUTO_INCREMENT,currencypairname VARCHAR(50),currencyexchangevalue DECIMAL(10, 5),currencyexchangechangevalue DECIMAL(10, 5),currencyexchangechangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                                  """CREATE TABLE IF NOT EXISTS indices (id INT AUTO_INCREMENT,indexname VARCHAR(120),indexvalue DECIMAL(30, 10),indexchangevalue DECIMAL(30, 10),indexchangepercentage VARCHAR(10),indexregion varchar(50),PRIMARY KEY (id));""",                                  
                                  """CREATE TABLE IF NOT EXISTS stocks (id INT AUTO_INCREMENT,stockname VARCHAR(120),stockvalue VARCHAR(55),stockchangevalue VARCHAR(55),stockchangepercentage VARCHAR(10),stocklabel varchar(50),PRIMARY KEY (id));""",
                                  """CREATE TABLE IF NOT EXISTS cryptocurrencies (id INT AUTO_INCREMENT,cryptoname VARCHAR(150),cryptovalue DECIMAL(30, 10),cryptochangevalue DECIMAL(30, 10),cryptochangepercentage VARCHAR(10),PRIMARY KEY (id));"""]

        # ## execute the above array to create tables
        for query in table_creation_queries:
            cursor.execute(query)
            print(query)
            print("Executed a table creation query.")
       
       ##Inserting data into the tables
        try:
            for _, row in df_currencies.iterrows():
                insert_query = "INSERT INTO currencies (currencypairname,currencyexchangevalue,currencyexchangechangevalue,currencyexchangechangepercentage) VALUES (%s, %s, %s,%s)"
                cursor.execute(insert_query, tuple(row))
            print("Inserted currencies")
            
            for _, row in df_crypto.iterrows():
                insert_query = "INSERT INTO cryptocurrencies (cryptoname,cryptovalue,cryptochangevalue,cryptochangepercentage) VALUES (%s, %s, %s,%s)"
                cursor.execute(insert_query, tuple(row))
            print("Inserted crypto-currencies")
                
            for _, row in df_american.iterrows():
                insert_query = "INSERT INTO indices (indexname,indexvalue,indexchangevalue,indexchangepercentage,indexregion) VALUES (%s, %s, %s,%s,'american')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted american")
                
            for _, row in df_asian.iterrows():
                insert_query = "INSERT INTO indices (indexname,indexvalue,indexchangevalue,indexchangepercentage,indexregion) VALUES (%s, %s, %s,%s,'asian')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted asian")
                
            for _, row in df_emea.iterrows():
                insert_query = "INSERT INTO indices (indexname,indexvalue,indexchangevalue,indexchangepercentage,indexregion) VALUES (%s, %s, %s,%s,'emea')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted emea")
            
            for _, row in df_loosers.iterrows():
                insert_query = "INSERT INTO stocks (stockname,stockvalue,stockchangevalue,stockchangepercentage,stocklabel) VALUES (%s, %s, %s,%s,'looser')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted loosers")
            
            
            for _, row in df_gainer.iterrows():
                insert_query = "INSERT INTO stocks (stockname,stockvalue,stockchangevalue,stockchangepercentage,stocklabel) VALUES (%s, %s, %s,%s,'gainer')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted gainer")
            
            
            for _, row in df_climate_leaders.iterrows():
                insert_query = "INSERT INTO stocks (stockname,stockvalue,stockchangevalue,stockchangepercentage,stocklabel) VALUES (%s, %s, %s,%s,'climate leader')"
                cursor.execute(insert_query, tuple(row))
            print("Inserted climate")
            
            ##commit the db values
            connection.commit()
        except Error as e:
            print(e)
        # print(df_crypto)
    except Error as e:
        print()
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

In [ ]:
import mysql.connector
from mysql.connector import Error
from sqlalchemy import create_engine
import pandas as pd


# Establishing the connection
try:
    
    # Establishing the connection to MySQL server (without specifying a database)
    connection = mysql.connector.connect(host='127.0.0.1',
                                          port=3309,
                                         database='webscrape',
                                         user='root',
                                         password='password',
                                         auth_plugin='mysql_native_password')
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
    
    # print(connection)
    cursor = connection.cursor()
    # List of table creation queries
    table_creation_queries = ["""CREATE TABLE IF NOT EXISTS currencies (id INT AUTO_INCREMENT,currencypair VARCHAR(50),exchangevalue DECIMAL(10, 5),exchangechangevalue DECIMAL(10, 5),exchangechangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS americanindex (id INT AUTO_INCREMENT,indexname VARCHAR(120),indexvalue DECIMAL(10, 5),indexchangevalue DECIMAL(10, 5),indexchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS asianindex (id INT AUTO_INCREMENT,indexname VARCHAR(120),indexvalue DECIMAL(10, 5),indexchangevalue DECIMAL(10, 5),indexchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS emeaindex (id INT AUTO_INCREMENT,indexname VARCHAR(120),indexvalue DECIMAL(10, 5),indexchangevalue DECIMAL(10, 5),indexchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS gainerstocks (id INT AUTO_INCREMENT,stockname VARCHAR(120),stockvalue DECIMAL(10, 5),stockchangevalue DECIMAL(10, 5),stockchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS looserstocks (id INT AUTO_INCREMENT,stockname VARCHAR(120),stockvalue DECIMAL(10, 5),stockchangevalue DECIMAL(10, 5),stockchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS climateleader (id INT AUTO_INCREMENT,stockname VARCHAR(120),stockvalue DECIMAL(10, 5),stockchangevalue DECIMAL(10, 5),stockchangepercentage VARCHAR(10),PRIMARY KEY (id));""",
                              """CREATE TABLE IF NOT EXISTS climateleaderstocks (id INT AUTO_INCREMENT,stockname VARCHAR(120),stockvalue DECIMAL(10, 5),stockchangevalue DECIMAL(10, 5),stockchangepercentage VARCHAR(10),PRIMARY KEY (id));"""]
    
    ## execute the above array to create tables
    for query in table_creation_queries:
        cursor.execute(query)
        print("Executed a table creation query.")

    # # Read the CSV file into a DataFrame again
    df_currencies = pd.read_csv('Currencies.csv')
    df_american_indices = pd.read_csv('America-Indexes.csv')
    df_emea_indices = pd.read_csv('EMEA-Indexes.csv')
    # # Replace 'old_name' with the current column name and 'new_name' with the new column name
    # df = df.rename(columns={'IndexName': 'currencypair', 'IndexValue': 'exchangevalue', 'IndexChangeValue': 'exchangechangevalue', 'IndexChangePercentage':'exchangechangepercentage'})
    # print(df)
    # # Step 2: Create a SQLAlchemy engine to connect to the MySQL database
    # engine = create_engine("mysql+mysqlconnector://root:password@localhost/webscrape", pool_size=20, max_overflow=0)
    # # result = cursor.execute(mySql_Create_Table_Query)
    # print(engine)
    # # Step 3: Convert the Pandas DataFrame to a format for MySQL table insertion
    # df.to_sql('currencies', con=engine, if_exists='append', index=False)

    # for _, row in df.iterrows():
    #     insert_query = "INSERT INTO currencies (currencypair,exchangevalue,exchangechangevalue,exchangechangepercentage) VALUES (%s, %s, %s,%s)"
    #     cursor.execute(insert_query, tuple(row))
    connection.commit()
    
except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

In [ ]:
######for the yahooo
###SQL Connections
try:
     # Establishing the connection to MySQL server (without specifying a database)
        connection = mysql.connector.connect(host='127.0.0.1',
                                             port=3309,
                                             database='webscrape',
                                             user='root',
                                             password='password',
                                             auth_plugin='mysql_native_password')
        if connection.is_connected():
            db_Info = connection.get_server_info()
            print("Connected to MySQL Server version ", db_Info)
            cursor = connection.cursor()
            cursor.execute("select database();")
            record = cursor.fetchone()
            print("You're connected to database: ", record)
            
            # print(connection)
        cursor = connection.cursor()
        table_creation_query = """CREATE TABLE IF NOT EXISTS crypto_currency (
                                  id INT AUTO_INCREMENT,
                                  symbol VARCHAR(50),
                                  name VARCHAR(255),
                                  priceintraday varchar(50),
                                  changevalue varchar(50),
                                  percentchange varchar(50),
                                  marketcap VARCHAR(50),
                                  volumeincurrencysinceutc varchar(50),
                                  volumeincurrency24hr varchar(50),
                                  totalvolumeallcurrencies24hr varchar(50),
                                  circulatingsupply varchar(15), PRIMARY KEY (id));"""
        cursor.execute(table_creation_query)
        
        ##Inserting data into the tables
        try:
            for _, row in df.iterrows():
                insert_query = "INSERT INTO crypto_currency(symbol,name,priceintraday,changevalue,percentchange,marketcap,volumeincurrencysinceutc,volumeincurrency24hr,totalvolumeallcurrencies24hr,circulatingsupply) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
                print(row)
                cursor.execute(insert_query, tuple(row))
             #Insert the rows   
            
            print("Inserted financial_data")
            ##commit the db values
            connection.commit()
            # print()
        except Error as e:
            print(e)
except Error as e:       
           print(e) 
finally:
        if connection.is_connected():
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

In [ ]:
### from central charts
###SQL Connections
try:
     # Establishing the connection to MySQL server (without specifying a database)
        connection = mysql.connector.connect(host='127.0.0.1',
                                             port=3309,
                                             database='webscrape',
                                             user='root',
                                             password='password',
                                             auth_plugin='mysql_native_password')
        if connection.is_connected():
            db_Info = connection.get_server_info()
            print("Connected to MySQL Server version ", db_Info)
            cursor = connection.cursor()
            cursor.execute("select database();")
            record = cursor.fetchone()
            print("You're connected to database: ", record)
            
            # print(connection)
        cursor = connection.cursor()
        table_creation_query = """CREATE TABLE IF NOT EXISTS central_charts_stock (
                                id INT AUTO_INCREMENT PRIMARY KEY,
                                name VARCHAR(255) NOT NULL,
                                current_price DECIMAL(15, 8) NOT NULL,
                                change_percentage DECIMAL(15, 8) NOT NULL,
                                open_price DECIMAL(15, 8) NOT NULL,
                                high_price DECIMAL(15, 8) NOT NULL,
                                low_price DECIMAL(15, 8) NOT NULL,
                                volume BIGINT NOT NULL);"""
        cursor.execute(table_creation_query)
        
        ##Inserting data into the tables
        try:
            for _, row in stock_df.iterrows():
                insert_query = "INSERT INTO central_charts_stock(name,current_price,change_percentage,open_price,high_price,low_price,volume) VALUES(%s,%s,%s,%s,%s,%s,%s)"
                print(row)
                cursor.execute(insert_query, tuple(row))
             #Insert the rows   
            
            print("Inserted central_charts stock data")
            ##commit the db values
            connection.commit()
            # print()
        except Error as e:
            print(e)
except Error as e:       
           print(e) 
finally:
        if connection.is_connected():
            cursor.close()
            connection.close()
            print("MySQL connection is closed")